import type { User } from "@/types/managment/managment";

const users: User[] = [
  {
    id: 1,
    name: "Nour Ali",
    email: "nour.ali@mail.com",
    status: "Active",
    role: "Learner",
    regDate: "2024-06-15",
  },
  {
    id: 2,
    name: "Omar Tarek",
    email: "omar.tarek@mail.com",
    status: "Blocked",
    role: "Instructor",
    regDate: "2024-05-12",
  },
  {
    id: 3,
    name: "Salma Ahmed",
    email: "salma.ahmed@mail.com",
    status: "Active",
    role: "Learner",
    regDate: "2024-05-10",
  },
  {
    id: 4,
    name: "Ahmed Hassan",
    email: "ahmed.hassan@mail.com",
    status: "Blocked",
    role: "Instructor",
    regDate: "2024-04-22",
  },
  {
    id: 5,
    name: "Mariam Youssef",
    email: "mariam.youssef@mail.com",
    status: "Active",
    role: "Learner",
    regDate: "2024-07-05",
  },
  {
    id: 6,
    name: "Khaled Mahmoud",
    email: "khaled.mahmoud@mail.com",
    status: "Active",
    role: "Instructor",
    regDate: "2024-03-11",
  },
  {
    id: 7,
    name: "Rana Samir",
    email: "rana.samir@mail.com",
    status: "Blocked",
    role: "Learner",
    regDate: "2024-02-14",
  },
  {
    id: 8,
    name: "Hassan Adel",
    email: "hassan.adel@mail.com",
    status: "Active",
    role: "Instructor",
    regDate: "2024-06-28",
  },
  {
    id: 9,
    name: "Layla Mohamed",
    email: "layla.mohamed@mail.com",
    status: "Active",
    role: "Learner",
    regDate: "2024-08-09",
  },
  {
    id: 10,
    name: "Youssef Karim",
    email: "youssef.karim@mail.com",
    status: "Blocked",
    role: "Instructor",
    regDate: "2024-01-31",
  },
  {
    id: 11,
    name: "Farida Ehab",
    email: "farida.ehab@mail.com",
    status: "Active",
    role: "Learner",
    regDate: "2024-09-02",
  },
  {
    id: 12,
    name: "Ali Nasser",
    email: "ali.nasser@mail.com",
    status: "Blocked",
    role: "Instructor",
    regDate: "2024-05-21",
  },
  {
    id: 13,
    name: "Hadeer Fathi",
    email: "hadeer.fathi@mail.com",
    status: "Active",
    role: "Learner",
    regDate: "2024-07-29",
  },
  {
    id: 14,
    name: "Mostafa Ibrahim",
    email: "mostafa.ibrahim@mail.com",
    status: "Blocked",
    role: "Instructor",
    regDate: "2024-06-01",
  },
  {
    id: 15,
    name: "Dina Ashraf",
    email: "dina.ashraf@mail.com",
    status: "Active",
    role: "Learner",
    regDate: "2024-03-19",
  },
];

export default users;
